config/routes.rb
Rails.application.routes.draw do
  resources :texts, only:[:index,:new,:create,:update,:edit,:destroy] do
    collection do
      post :confirm
    end
  end
  
  root'top#index'

end

app/models/text.rb
class Text < ActiveRecord::Base
 validates :content,presence: true, length: {maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text,only:[:edit,:update,:destroy]
  
  def index
    @texts = Text.all
  end
  
  def new
    if params[:back]
     @text = Text.new(texts_params)
    else
     @text = Text.new
    end
  end
  
  def create
    @text = Text.new(texts_params)
    if @text.save
     redirect_to texts_path,notice:"Successful tweet！"
    else
     render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if  @text.update(texts_params)
      redirect_to texts_path,notice:"Successfully edited tweet！"
    else
      render'edit'
    end
  end
  
  def destroy
   @text.destroy
   redirect_to texts_path,notice:"Deleted tweet！"
  end
  
  def confirm
    @text = Text.new(texts_params)
    render 'new' if @text.invalid?
  end
  
  private
  def texts_params
    params.require(:text).permit(:content)
  end
  
  def set_text
   @text = Text.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/texts_helper.rb
module TextsHelper
 def choose_new_or_edit
  if action_name == 'new' || action_name == 'confirm'
   confirm_texts_path
  elsif action_name == 'edit'
   text_path
  end
 end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soliloquence</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to"Soliloquence",root_path,class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
       <li><%= link_to "Index",texts_path %></li>
       <li>
        <button class="btn btn-default navbar-btn" type="button">
            <%= link_to "Tweet",new_text_path %>
        </buton>
       </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <% flash.each do |key, value| %>
      <% key = "info" if key == "notice" %>
      <% key = "danger"  if key == "alert" %>
      <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
  
<%= yield %>


  <footer>
   <p><strong>made by T.O since 2017</strong></p>
  </footer>

</body>
</html>

app/views/texts/_form.html.erb
<%= form_for(@text,url: choose_new_or_edit) do |f| %>
 <% if @text.errors.any? %>
  <div class="alert alert-danger alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
   <h2><%= @text.errors.count %>件のエラーがあります</h2>
   <ul style="list-style:none">
    <% @text.errors.full_messages.each do |msg|%>
    <li><%= msg %></li>
    <% end %>
   </ul>
  </div>
 <% end %>

  <%= f.label :content %>
  <%= f.text_field :content, :class => "form-control",:rows => 3 , :placeholder => "Please enter a tweet here." %>
 <br>
 <%= f.submit"Submit", class:"btn btn-success btn-border"%> <%= link_to "To history list",texts_path, class: "btn btn-warning btn-border" %>
<% end %>

app/views/texts/confirm.html.erb
<div class="container">
 <div class=" col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
  <h1>Confirm with this content ?</h1>
  <div class="confirm-group">
   <%=form_for(@text) do |f| %>
    <%= f.hidden_field :content %>
    <div class="confirm-box">
     <%= @text.content %>
    </div>
    <%= f.submit"confirm",class:"confirm-btn btn-success btn-border"%>
   <% end %>
   <%=form_for(@text,url: new_text_path, method:'get') do |f| %>
    <%= f.hidden_field :content %> 
    <%= f.submit"back",name:'back',class:"confirm-btn2 btn-warning btn-border" %>
   <% end %>
  </div>
 </div>
</div>

app/views/texts/edit.html.erb
<div class="container">
 <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
  <h1>Edit tweets</h1>
  <%= render 'form' %>
 </div>
</div>

app/views/texts/index.html.erb
 <h1>History list</h1> 
<div class="container">
  <div class="row">
    <% @texts.each do |text| %>
    <div class="one-tweet col-md-4 col-sm-10 col-ofset-2">
     <div class= "tweet-box">
      <p><%= text.content %></p>
      <p><%= text.created_at.strftime("%Y年%m月%d日 %H時%M分") %></p>
     <%= link_to "Edit",edit_text_path(text.id),class:"btn btn-success btn-border" %>
     <%= link_to "Delete",text_path(text.id),method: :delete,class:"btn btn-danger btn-border", data:{confirm:"本当に削除しますか？"} %>
     </div>
   </div>
   <% end %>
  </div>
</div>

app/views/texts/new.html.erb
<div class="container">
 <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
  <h1>Tweet</h1>
  <%= render 'form' %>
 </div>
</div>

app/views/top/index.html.erb
<section class="about">
<h1>Soliloquence</h1>
<p>You can say it when you want to say something to say.</p>
<p>言いたい事を言いたい時に言おう</p>
</section>